### ISSUE TITLE
Can't build on debian10

### ISSUE THREAD

**Issue by hackson99** [tomaspinho/rtl8821ce#60]
Hi,
after i finished make , i got error:
/home/wjm/Templates/rtl8821ce-git20190810/os_dep/linux/rtw_android.c: In function ‘rtw_android_priv_cmd’:
/home/wjm/Templates/rtl8821ce-git20190810/os_dep/linux/rtw_android.c:665:49: error: macro "access_ok" requires 3 arguments, but only 2 given
  if (!access_ok(priv_cmd.buf, priv_cmd.total_len)) {
                                                 ^
/home/wjm/Templates/rtl8821ce-git20190810/os_dep/linux/rtw_android.c:665:7: error: ‘access_ok’ undeclared (first use in this function)
  if (!access_ok(priv_cmd.buf, priv_cmd.total_len)) {
       ^~~~~~~~~
/home/wjm/Templates/rtl8821ce-git20190810/os_dep/linux/rtw_android.c:665:7: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [/usr/src/linux-headers-4.19.0-5-common/scripts/Makefile.build:309：/home/wjm/Templates/rtl8821ce-git20190810/os_dep/linux/rtw_android.o] error 1
make[3]: *** [/usr/src/linux-headers-4.19.0-5-common/Makefile:1539：_module_/home/wjm/Templates/rtl8821ce-git20190810] error 2
make[2]: *** [Makefile:146：sub-make] error 2
make[1]: *** [Makefile:8：all] error  2
make[1]: leave “/usr/src/linux-headers-4.19.0-5-amd64”
make: *** [Makefile:2237：modules] error 2

I need some guide,Thanks a lot!'

**Comment by tomaspinho** [comment]
Will work on this later this week. This is a regression caused by the merging of upstream drivers. This issue had already been fixed in the past.

**Comment by hackson99** [comment]
Thanks a lot.

In  debian-laptop mail-list, herve told me to change some code in rtw_android.c as the following will work:

#if  (LINUX_VERSION_CODE < KERNEL_VERSION(5, 0, 0))
         if  (!access_ok(VERIFY_READ, priv_cmd.buf, priv_cmd.total_len)) {
#else
         if  (!access_ok(priv_cmd.buf, priv_cmd.total_len)) {
#endif/* Linux kernel < 5.0.0 */

U can check https://github.com/aircrack-ng/rtl8812au/issues/301

Maybe can help u.

**Comment by tomaspinho** [comment]
Thanks to @rkitover we have a fix for this. 🎉 

Can you verify?
https://github.com/tomaspinho/rtl8821ce/pull/61

**Comment by hackson99** [comment]
OK! It doe's work!

Thanks a lot!

**Comment by chaitanyaGa** [comment]
still getting same issue on Ubuntu

ERROR (dkms apport): binary package for rtl8821ce: v5.5.2_34066.20190614 not found

Machine Details:
sherlock@success-Lenovo-IdeaPad-S145:~/Downloads/rtl/rtl8821ce$ uname -r
5.3.0-40-generic
sherlock@success-Lenovo-IdeaPad-S145:~/Downloads/rtl/rtl8821ce$ uname
Linux
sherlock@success-Lenovo-IdeaPad-S145:~/Downloads/rtl/rtl8821ce$ uname -a
Linux success-Lenovo-IdeaPad-S145 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
